theme: jekyll-theme-cayman

title: Nam Le Nhut
description: Project to learning JavaScript
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nam Le Nhut
user_description: ""
email: namle1232000@gmail.com
twitter_username: Namlee298
github_username: lenhutnam298
gplus_username: LeNam 